export const COLOR_OPTIONS = [
  { value: "#3F7F4E", label: "Army Green" },
  { value: "#333333", label: "Asphalt" },
  { value: "#A1C9F2", label: "Baby Blue" },
  { value: "#000000", label: "Black" },
  { value: "#0000ff", label: "Blue" },
  { value: "#032B44", label: "Blue Navy" },
  { value: "#964B00", label: "Brown" },
  { value: "#4d4d4f", label: "Charcoal" },
  { value: "#FF0033", label: "Cherry Red" },
  { value: "#964B00", label: "Coffee" },
  { value: "#8B0A1A", label: "Cranberry" },
  { value: "#5C5C5C", label: "Deep Heather" },
  { value: "#333333", label: "Dark Grey" },
  { value: "#38373b", label: "Dark Heather" },
  { value: "#03055B", label: "Darkest Blue" },
  { value: "#228B22", label: "Forest Green" },
  { value: "#FFC0CB", label: "Fuschia" },
  { value: "#FFD700", label: "Gold" },
  { value: "#808080", label: "Gray" },
  { value: "#666666", label: "Gravel" },
  { value: "#008000", label: "Green" },
  { value: "#333333", label: "Heather Black" },
  { value: "#87CEEB", label: "Heather Blue" },
  { value: "#C7C5B8", label: "Heather Grey" },
  { value: "#3E8E41", label: "Heather Green" },
  { value: "#3E8E41", label: "Heather Irish Green" },
  { value: "#C51077", label: "Heather Maroon" },
  { value: "#FFD7BE", label: "Heather Peach" },
  { value: "#34C759", label: "Kelly" },
  { value: "#34C759", label: "Kelly Green" },
  { value: "#ADD8E6", label: "Light Blue" },
  { value: "#FFC5C5", label: "Light Pink" },
  { value: "#AFEEEE", label: "Light Turquoise" },
  { value: "#6b2e4d", label: "Maroon" },
  { value: "#6d644b", label: "Military Green" },
  { value: "#5C7135", label: "Moss Green" },
  { value: "#FF69B4", label: "Neon Pink" },
  { value: "#808000", label: "Olive" },
  { value: "#FFA07A", label: "Orange" },
  { value: "#FFC0CB", label: "Pink" },
  { value: "#800080", label: "Purple" },
  { value: "#d2151f", label: "Red" },
  { value: "#4169E1", label: "Royal" },
  { value: "#4169E1", label: "Royal Blue" },
  { value: "#32CD32", label: "Safety Green" },
  { value: "#C0C0C0", label: "Silver" },
  { value: "#708090", label: "Slate" },
  { value: "#8b8b8b", label: "Sport Grey" },
  { value: "#87CEEB", label: "Vintage Heather Blue" },
  { value: "#032B44", label: "Vintage Heather Navy" },
  { value: "#ffffff", label: "White" },
  { value: "#FFFF00", label: "Yellow" },
  { value: "#F4F4F4", label: "Sand" },
  { value: "#B2B2B2", label: "Ash Grey" },
];

export const SIZE_OPTIONS = [
  { value: "S", label: "S" },
  { value: "M", label: "M" },
  { value: "L", label: "L" },
  { value: "XL", label: "XL" },
  { value: "2XL", label: "2XL" },
  { value: "3XL", label: "3XL" },
  { value: "4XL", label: "4XL" },
  { value: "5XL", label: "5XL" },
  { value: "XXL", label: "XXL" },
  { value: "Twin (172*220 cm)", label: "Twin (172*220 cm)" },
  { value: "Queen (200*230 cm)", label: "Queen (200*230 cm)" },
  { value: "Square (228*228 cm)", label: "Square (228*228 cm)" },
  { value: "King (229*259 cm)", label: "King (229*259 cm)" },
  { value: "Normal Tumbler 12oz", label: "Normal Tumbler 12oz" },
  { value: "Normal Tumbler 17oz", label: "Normal Tumbler 17oz" },
  { value: "Normal Tumbler 20oz", label: "Normal Tumbler 20oz" },
  { value: "Normal Tumbler 30oz", label: "Normal Tumbler 30oz" },
  { value: "Glitter Tumbler 20oz", label: "Glitter Tumbler 20oz" },
  { value: "Glitter Tumbler 30oz", label: "Glitter Tumbler 30oz" },
  { value: "12x16 inches", label: "12x16 inches" },
  { value: "20x28 inches", label: "20x28 inches" },
  { value: "28x20 inches", label: "28x20 inches" },
  { value: "24x32 inches", label: "24x32 inches" },
  { value: "32x24 inches", label: "32x24 inches" },
  { value: "Kid", label: "Kid" },
  { value: "Adult", label: "Adult" },
  { value: "11OZ", label: "11OZ" },
  { value: "15OZ", label: "15OZ" },
  { value: "90*180cm", label: "90*180cm" },
  { value: "120*180cm", label: "120*180cm" },
  { value: "150*180cm", label: "150*180cm" },
  { value: "165*180cm", label: "165*180cm" },
  { value: "180*180cm", label: "180*180cm" },
  { value: "180*200cm", label: "180*200cm" },
  { value: "92cmx153cm", label: "92cmx153cm" },
  { value: "122cmx180cm", label: "122cmx180cm" },
  { value: "153cmx244cm", label: "153cmx244cm" },
  { value: '24"x16" inches', label: '24"x16" inches' },
  { value: '12"x8" inches', label: '12"x8" inches' },
  { value: '18"x12" inches', label: '18"x12" inches' },
  { value: "17cm (6.7 inch)", label: "17cm (6.7 inch)" },
  { value: "19cm (7.5 inch)", label: "19cm (7.5 inch)" },
  { value: "21cm (8.3 inch)", label: "21cm (8.3 inch)" },
  { value: "5(U.S)", label: "5(U.S)" },
  { value: "6(U.S)", label: "6(U.S)" },
  { value: "7(U.S)", label: "7(U.S)" },
  { value: "8(U.S)", label: "8(U.S)" },
  { value: "9(U.S)", label: "9(U.S)" },
  { value: "10(U.S)", label: "10(U.S)" },
  { value: "11(U.S)", label: "11(U.S)" },
  { value: "12(U.S)", label: "12(U.S)" },
  { value: "13(U.S)", label: "13(U.S)" },
  { value: "8mm", label: "8mm" },
  { value: "10mm", label: "10mm" },
  { value: "12mm", label: "12mm" },
  { value: "14mm", label: "14mm" },
  { value: "16mm", label: "16mm" },
  { value: "18mm", label: "18mm" },
  { value: "20mm", label: "20mm" },
  { value: "S(26-38CM)", label: "S(26-38CM)" },
  { value: "M(38-48CM)", label: "M(38-48CM)" },
  { value: "L(46-58CM)", label: "L(46-58CM)" },
  { value: "XL(56-68CM)", label: "XL(56-68CM)" },
  { value: "Garden Flag (11.5x17.5)", label: "Garden Flag (11.5x17.5)" },
  { value: "House Flag (29.5x39.5)", label: "House Flag (29.5x39.5)" },
  { value: "40cmx60cm", label: "40cmx60cm" },
  { value: "40cmx65cm", label: "40cmx65cm" },
  { value: "45cmx75cm", label: "45cmx75cm" },
  { value: "55cmx90cm", label: "55cmx90cm" },
  { value: "23.6x15.7", label: "23.6x15.7" },
  { value: "30x18", label: "30x18" },
  { value: "52x63", label: "52x63" },
  { value: "52x84", label: "52x84" },
  { value: "52x95", label: "52x95" },
  { value: "52x108", label: "52x108" },
  { value: "52x120", label: "52x120" },
  { value: "Small", label: "Small" },
  { value: "Medium", label: "Medium" },
  { value: "Large", label: "Large" },
  { value: "X-Large", label: "X-Large" },
  { value: "XX-Large", label: "XX-Large" },
  { value: "3X-Large", label: "3X-Large" },
  { value: "6X-Large", label: "6X-Large" },
  { value: "10-12 Years", label: "10-12 Years" },
  { value: "14-16 Years", label: "14-16 Years" },
  { value: "16-18 Years", label: "16-18 Years" },
  { value: "CH", label: "CH" },
  { value: "G", label: "G" },
  { value: "X-Small", label: "X-Small" },
  { value: "Kids 2", label: "Kids 2" },
  { value: "Kids 3", label: "Kids 3" },
  { value: "Kids 4", label: "Kids 4" },
  { value: "Kids 6", label: "Kids 6" },
  { value: "Kids 8", label: "Kids 8" },
  { value: "Kids 10", label: "Kids 10" },
  { value: "Kids 12", label: "Kids 12" },
  { value: "4T", label: "4T" },
  { value: "5-6 Years", label: "5-6 Years" },
  { value: "4", label: "4" },
  { value: "6-8", label: "6-8" },
];

export const TYPE_OPTIONS = [
  { value: "Men", label: "Men" },
  { value: "Women", label: "Women" },
  { value: "Youth", label: "Youth" },
  { value: "Hooded Sweatshirt", label: "Hooded Sweatshirt" },
  { value: "T-shirt", label: "T-shirt" },
  { value: "Unisex", label: "Unisex" },
  { value: "Hoodie", label: "Hoodie" },
  { value: "Sweatshirt", label: "Sweatshirt" },
  { value: "Kids", label: "Kids" },
  { value: "Bodysuit", label: "Bodysuit" },
  { value: "Mom", label: "Mom" },
  { value: "Dad", label: "Dad" },
  { value: "No customize", label: "No customize" },
  { value: "Hoodie ($32.29 - $38.24)", label: "Hoodie ($32.29 - $38.24)" },
  {
    value: "Zipped Hoodie ($33.99 - $39.94)",
    label: "Zipped Hoodie ($33.99 - $39.94)",
  },
  { value: "iPhone 8", label: "iPhone 8" },
  { value: "iPhone 8 Plus", label: "iPhone 8 Plus" },
  { value: "iPhone XS", label: "iPhone XS" },
  { value: "iPhone XS MAX", label: "iPhone XS MAX" },
  { value: "iPhone XR", label: "iPhone XR" },
  { value: "iPhone X", label: "iPhone X" },
  { value: "iPhone 11 Pro Max", label: "iPhone 11 Pro Max" },
  { value: "iPhone 11 Pro", label: "iPhone 11 Pro" },
  { value: "iPhone 11", label: "iPhone 11" },
  { value: "iPhone 12 Pro Max", label: "iPhone 12 Pro Max" },
  { value: "iPhone 12 Pro", label: "iPhone 12 Pro" },
  { value: "iPhone 12 Mini", label: "iPhone 12 Mini" },
  { value: "iPhone 12", label: "iPhone 12" },
  { value: "iPhone 13 Pro Max", label: "iPhone 13 Pro Max" },
  { value: "iPhone 13 Pro", label: "iPhone 13 Pro" },
  { value: "iPhone 13 Mini", label: "iPhone 13 Mini" },
  { value: "iPhone 13", label: "iPhone 13" },
  { value: "Samsung Galaxy S10", label: "Samsung Galaxy S10" },
  { value: "Samsung Galaxy S10E", label: "Samsung Galaxy S10E" },
  { value: "Samsung Galaxy S10 Plus", label: "Samsung Galaxy S10 Plus" },
  { value: "Samsung Galaxy S20", label: "Samsung Galaxy S20" },
  { value: "Samsung Galaxy S20+", label: "Samsung Galaxy S20+" },
  { value: "Samsung Galaxy S20 Ultra", label: "Samsung Galaxy S20 Ultra" },
  { value: "Coffee Mug", label: "Coffee Mug" },
  { value: "Travel Mug", label: "Travel Mug" },
  { value: "Female", label: "Female" },
  { value: "Male", label: "Male" },
  { value: "iPhone 8 / SE (2020)", label: "iPhone 8 / SE (2020)" },
  { value: "Galaxy S9", label: "Galaxy S9" },
  { value: "iPhone 7", label: "iPhone 7" },
  { value: "iPhone 7 Plus", label: "iPhone 7 Plus" },
  { value: "iPhone 6", label: "iPhone 6" },
  { value: "iPhone 6 Plus", label: "iPhone 6 Plus" },
  { value: "iPhone SE (2016)", label: "iPhone SE (2016)" },
  { value: "iPhone 5", label: "iPhone 5" },
  { value: "Circle", label: "Circle" },
  { value: "Oval", label: "Oval" },
  { value: "Horizontal", label: "Horizontal" },
  { value: "Vertical", label: "Vertical" },
  { value: "Bell", label: "Bell" },
  { value: "Christmas Stocking", label: "Christmas Stocking" },
  { value: "Heart", label: "Heart" },
  { value: "Star", label: "Star" },
  { value: "Tree", label: "Tree" },
  { value: "Unissexo", label: "Unissexo" },
  { value: "iPhone SE (2020)/8", label: "iPhone SE (2020)/8" },
  { value: "iPhone 6s", label: "iPhone 6s" },
  { value: "iPhone 6s Plus", label: "iPhone 6s Plus" },
  { value: "iPhone SE (2016)/5s/5", label: "iPhone SE (2016)/5s/5" },
  { value: "iPhone 5c", label: "iPhone 5c" },
  { value: "iPhone 4s/4", label: "iPhone 4s/4" },
  { value: "iPhone XR", label: "iPhone XR" },
  { value: "Galaxy S6", label: "Galaxy S6" },
  { value: "iPhone 12", label: "iPhone 12" },
  { value: "iPhone 12 mini", label: "iPhone 12 mini" },
  { value: "iPhone 12 Pro", label: "iPhone 12 Pro" },
  { value: "iPhone 12 Pro Max", label: "iPhone 12 Pro Max" },
  { value: "iPhone 8 / SE (2020)", label: "iPhone 8 / SE (2020)" },
  { value: "Galaxy S8", label: "Galaxy S8" },
  { value: "iPhone 8 Plus", label: "iPhone 8 Plus" },
  { value: "iPhone 11 Pro", label: "iPhone 11 Pro" },
  { value: "iPhone 11 Pro Max", label: "iPhone 11 Pro Max" },
  { value: "iPhone 11", label: "iPhone 11" },
  { value: "Galaxy S9", label: "Galaxy S9" },
  { value: "iPhone 7", label: "iPhone 7" },
  { value: "iPhone 7 Plus", label: "iPhone 7 Plus" },
  { value: "iPhone XS", label: "iPhone XS" },
  { value: "iPhone XS Max", label: "iPhone XS Max" },
  { value: "iPhone 13 Pro", label: "iPhone 13 Pro" },
  { value: "iPhone 13 Pro Max", label: "iPhone 13 Pro Max" },
  { value: "iPhone 13", label: "iPhone 13" },
  { value: "iPhone 13 mini", label: "iPhone 13 mini" },
  { value: "iPhone 13 mini", label: "iPhone 13 mini" },
  { value: "iPhone 6", label: "iPhone 6" },
  { value: "iPhone 6 Plus", label: "iPhone 6 Plus" },
  { value: "iPhone SE (2016)", label: "iPhone SE (2016)" },
  { value: "Galaxy S7", label: "Galaxy S7" },
  { value: "iPhone X", label: "iPhone X" },
  { value: "iPhone 5", label: "iPhone 5" },
  { value: "iPhone SE (2020)/8", label: "iPhone SE (2020)/8" },
  { value: "iPhone 6s", label: "iPhone 6s" },
  { value: "iPhone 6s Plus", label: "iPhone 6s Plus" },
  { value: "iPhone SE (2016)/5s/5", label: "iPhone SE (2016)/5s/5" },
];
export const IMAGE_DIMENSIONS = {
  width: "100px",
  height: "100px",
};

export const EDITOR_CONFIG = {
  toolbar: [
    "heading",
    "|",
    "bold",
    "italic",
    "link",
    "bulletedList",
    "numberedList",
    "|",
    "outdent",
    "indent",
    "|",
    "blockQuote",
    "insertTable",
    "undo",
    "redo",
  ],
};
